---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - supabase.com
  resources:
  - supabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - supabase.com
  resources:
  - supabases/finalizers
  verbs:
  - update
- apiGroups:
  - supabase.com
  resources:
  - supabases/status
  verbs:
  - get
  - patch
  - update
