# permissions for end users to edit supabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: supabase-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: supabase-operator
    app.kubernetes.io/part-of: supabase-operator
    app.kubernetes.io/managed-by: kustomize
  name: supabase-editor-role
rules:
- apiGroups:
  - supabase.com
  resources:
  - supabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - supabase.com
  resources:
  - supabases/status
  verbs:
  - get
