apiVersion: supabase.com/v1
kind: Supabase
metadata:
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: supabase-sample
    app.kubernetes.io/part-of: supabase-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: supabase-operator
  name: supabase-sample
spec:
  # TODO(user): Add fields here
